# Upstream issue labels to copy to our issues.
[labels]
color = "c5def5"
prefixes = ["css-", "SVG", "selectors", "resize-"]

# Bugzilla component in which to file bugs, based on issue label.
[components]
default = "Core :: Layout"
css-animations = "Core :: CSS Transitions and Animations"
css-backgrounds = "Core :: Layout: Images, Video, and HTML Frames"
css-box = "Core :: Layout: Block and Inline"
css-cascade = "Core :: CSS Parsing and Computation"
css-conditional = "Core :: CSS Parsing and Computation"
css-content = "Core :: Layout: Generated Content, Lists, and Counters"
css-counter-styles = "Core :: Layout: Generated Content, Lists, and Counters"
css-easing = "Core :: CSS Transitions and Animations"
css-env = "Core :: CSS Parsing and Computation"
css-fill-and-stroke = "Core :: SVG"
css-flexbox = "Core :: Layout: Positioned"
css-floats = "Core :: Layout: Floats"
css-font-loading = "Core :: Layout: Text and Fonts"
css-fonts = "Core :: Layout: Text and Fonts"
css-forms = "Core :: Layout: Form Controls"
css-grid = "Core :: Layout: Positioned"
css-images = "Core :: Layout: Images, Video, and HTML Frames"
css-inline = "Core :: Layout: Block and Inline"
css-lists = "Core :: Layout: Generated Content, Lists, and Counters"
css-multicol = "Core :: Layout: Columns"
css-namespaces = "Core :: CSS Parsing and Computation"
css-nesting = "Core :: CSS Parsing and Computation"
cssom = "Core :: DOM: CSS Object Model"
cssom-view = "Core :: DOM: CSS Object Model"
css-overflow = "Core :: Layout: Scrolling and Overflow"
css-overscroll-behavior = "Core :: Layout: Scrolling and Overflow"
css-position = "Core :: Layout: Positioned"
css-ruby = "Core :: Layout: Ruby"
css-scoping = "Core :: CSS Parsing and Computation"
css-scroll-anchoring = "Core :: Layout: Scrolling and Overflow"
css-scrollbars = "Core :: Layout: Scrolling and Overflow"
css-shadow-parts = "Core :: CSS Parsing and Computation"
css-shapes = "Core :: Layout: Floats"
css-syntax = "Core :: CSS Parsing and Computation"
css-tables = "Core :: Layout: Tables"
css-text = "Core :: Layout: Text and Fonts"
css-text-decor = "Core :: Layout: Text and Fonts"
css-transitions = "Core :: CSS Transitions and Animations"
css-values = "Core :: CSS Parsing and Computation"
css-variables = "Core :: CSS Parsing and Computation"
mediaqueries = "Core :: CSS Parsing and Computation"
motion = "Core :: CSS Transitions and Animations"
selectors = "Core :: CSS Parsing and Computation"
selectors-nonelement = "Core :: CSS Parsing and Computation"
SVG = "Core :: SVG"
web-animations = "Core :: DOM: Animation"
web-animations-css-integration = "Core :: DOM: Animation"
